version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=goldAndSilver
      - MYSQL_USER=tin
      - MYSQL_PASSWORD=123
    ports:
      - "32000:3306"

