version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE= goldAndSilver
      - MYSQL_USER= root
      - MYSQL_PASSWORD= root
    ports:
      - 32000:3306


